language: ruby
rvm:
 - 1.9.3

before_install:
  - "mysql -e 'create database tracks_test;'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/site.yml.tmpl config/site.yml"
  - "cp config/database.yml.tmpl config/database.yml"

script: "bundle exec rake ci"

bundler_args: --without development
notifications:
  recipients:
    - tracksapp@googlegroups.com

