#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Depot::Application.load_tasks

namespace :rk do
  task :echo => :environment do
    puts 'Pola...' + mydesc(Product.new)
    puts 'Pola...' + mydesc(Cart.new)
    puts 'Pola...' + mydesc(LineItem.new)
  end

  def mydesc(o)
   o.inspect
  end
end
